{"name": "testcase description", "status": "broken", "statusDetails": {"message": "httprunner.exceptions.ValidationFailure: assert text contains 登录失败，请检查您的用户名或密码是否填写正确(str)\t==> fail\ncheck_item: text\ncheck_value: <html><meta charset='utf-8'/><style>body{background:white}</style><script>alert('ç»å½å¤±è´¥ï¼è¯·æ£æ¥æ¨çç¨æ·åæå¯ç æ¯å¦å¡«åæ­£ç¡®ã')\n</script>\n<html><meta charset='utf-8'/><style>body{background:white}</style><script>if(window.parent) window.parent.document.body.click();\n</script>\n(str)\nassert_method: contains\nexpect_value: 登录失败，请检查您的用户名或密码是否填写正确(str)", "trace": "login_logout_test.py:36: in test_start\n    super().test_start(param)\n..\\..\\venv\\lib\\site-packages\\httprunner\\runner.py:455: in test_start\n    return self.run_testcase(\n..\\..\\venv\\lib\\site-packages\\httprunner\\runner.py:357: in run_testcase\n    extract_mapping = self.__run_step(step)\n..\\..\\venv\\lib\\site-packages\\httprunner\\runner.py:297: in __run_step\n    step_data = self.__run_step_testcase(step)\n..\\..\\venv\\lib\\site-packages\\httprunner\\runner.py:246: in __run_step_testcase\n    testcase_cls()\n..\\..\\venv\\lib\\site-packages\\httprunner\\runner.py:384: in run\n    return self.run_testcase(testcase_obj)\n..\\..\\venv\\lib\\site-packages\\httprunner\\runner.py:357: in run_testcase\n    extract_mapping = self.__run_step(step)\n..\\..\\venv\\lib\\site-packages\\httprunner\\runner.py:295: in __run_step\n    step_data = self.__run_step_request(step)\n..\\..\\venv\\lib\\site-packages\\httprunner\\runner.py:208: in __run_step_request\n    resp_obj.validate(\n..\\..\\venv\\lib\\site-packages\\httprunner\\response.py:271: in validate\n    raise ValidationFailure(failures_string)\nE   httprunner.exceptions.ValidationFailure: assert text contains 登录失败，请检查您的用户名或密码是否填写正确(str)\t==> fail\nE   check_item: text\nE   check_value: <html><meta charset='utf-8'/><style>body{background:white}</style><script>alert('ç»å½å¤±è´¥ï¼è¯·æ£æ¥æ¨çç¨æ·åæå¯ç æ¯å¦å¡«åæ­£ç¡®ã')\nE   </script>\nE   <html><meta charset='utf-8'/><style>body{background:white}</style><script>if(window.parent) window.parent.document.body.click();\nE   </script>\nE   (str)\nE   assert_method: contains\nE   expect_value: 登录失败，请检查您的用户名或密码是否填写正确(str)"}, "description": "TestCase ID: 0af19024-ee8e-4773-82d9-6ac1213d2f08", "steps": [{"name": "step: login_$case", "status": "broken", "statusDetails": {"message": "httprunner.exceptions.ValidationFailure: assert text contains 登录失败，请检查您的用户名或密码是否填写正确(str)\t==> fail\ncheck_item: text\ncheck_value: <html><meta charset='utf-8'/><style>body{background:white}</style><script>alert('ç»å½å¤±è´¥ï¼è¯·æ£æ¥æ¨çç¨æ·åæå¯ç æ¯å¦å¡«åæ­£ç¡®ã')\n</script>\n<html><meta charset='utf-8'/><style>body{background:white}</style><script>if(window.parent) window.parent.document.body.click();\n</script>\n(str)\nassert_method: contains\nexpect_value: 登录失败，请检查您的用户名或密码是否填写正确(str)\n", "trace": "  File \"d:\\testdev\\workspace\\python\\venv\\lib\\site-packages\\httprunner\\runner.py\", line 357, in run_testcase\n    extract_mapping = self.__run_step(step)\n  File \"d:\\testdev\\workspace\\python\\venv\\lib\\site-packages\\httprunner\\runner.py\", line 297, in __run_step\n    step_data = self.__run_step_testcase(step)\n  File \"d:\\testdev\\workspace\\python\\venv\\lib\\site-packages\\httprunner\\runner.py\", line 246, in __run_step_testcase\n    testcase_cls()\n  File \"d:\\testdev\\workspace\\python\\venv\\lib\\site-packages\\httprunner\\runner.py\", line 384, in run\n    return self.run_testcase(testcase_obj)\n  File \"d:\\testdev\\workspace\\python\\venv\\lib\\site-packages\\httprunner\\runner.py\", line 357, in run_testcase\n    extract_mapping = self.__run_step(step)\n  File \"d:\\testdev\\workspace\\python\\venv\\lib\\site-packages\\httprunner\\runner.py\", line 295, in __run_step\n    step_data = self.__run_step_request(step)\n  File \"d:\\testdev\\workspace\\python\\venv\\lib\\site-packages\\httprunner\\runner.py\", line 208, in __run_step_request\n    resp_obj.validate(\n  File \"d:\\testdev\\workspace\\python\\venv\\lib\\site-packages\\httprunner\\response.py\", line 271, in validate\n    raise ValidationFailure(failures_string)\n"}, "steps": [{"name": "step: login_$case", "status": "broken", "statusDetails": {"message": "httprunner.exceptions.ValidationFailure: assert text contains 登录失败，请检查您的用户名或密码是否填写正确(str)\t==> fail\ncheck_item: text\ncheck_value: <html><meta charset='utf-8'/><style>body{background:white}</style><script>alert('ç»å½å¤±è´¥ï¼è¯·æ£æ¥æ¨çç¨æ·åæå¯ç æ¯å¦å¡«åæ­£ç¡®ã')\n</script>\n<html><meta charset='utf-8'/><style>body{background:white}</style><script>if(window.parent) window.parent.document.body.click();\n</script>\n(str)\nassert_method: contains\nexpect_value: 登录失败，请检查您的用户名或密码是否填写正确(str)\n", "trace": "  File \"d:\\testdev\\workspace\\python\\venv\\lib\\site-packages\\httprunner\\runner.py\", line 357, in run_testcase\n    extract_mapping = self.__run_step(step)\n  File \"d:\\testdev\\workspace\\python\\venv\\lib\\site-packages\\httprunner\\runner.py\", line 295, in __run_step\n    step_data = self.__run_step_request(step)\n  File \"d:\\testdev\\workspace\\python\\venv\\lib\\site-packages\\httprunner\\runner.py\", line 208, in __run_step_request\n    resp_obj.validate(\n  File \"d:\\testdev\\workspace\\python\\venv\\lib\\site-packages\\httprunner\\response.py\", line 271, in validate\n    raise ValidationFailure(failures_string)\n"}, "start": 1617910635070, "stop": 1617910635110}], "start": 1617910635069, "stop": 1617910635111}], "attachments": [{"name": "stderr", "source": "20bc26c9-61c5-4049-af84-817cbac11568-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "param", "value": "{'case': '账号为空', 'account': '', 'password': '333333', 'expect': '登录失败，请检查您的用户名或密码是否填写正确'}"}], "start": 1617910635065, "stop": 1617910635112, "uuid": "eb303643-e53b-425a-8474-35cd53aa4448", "historyId": "714ddd6ddc49f526153124ea0119ffa7", "testCaseId": "0ff37cc6b093ec5364e073de52118526", "fullName": "login_logout_test.TestCaseLoginLogout#test_start", "labels": [{"name": "suite", "value": "login_logout_test"}, {"name": "subSuite", "value": "TestCaseLoginLogout"}, {"name": "host", "value": "loong"}, {"name": "thread", "value": "3472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login_logout_test"}]}